config/routes.rb
Rails.application.routes.draw do
  get 'rename/categories'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profiles'
    post 'profiles', to: 'users/registrations#create_profiles'
  end
  
  root 'items#index'
  resources :credit_cards, only:[:new]
  resources :mypage, only:[:new]
  resources :address, only:[:new]
  resources :inquiry, only:[:new]
  resources :logout, only:[:new]
  resources :mail_password, only:[:new]
  resources :profile, only:[:new]
  resources :user_info, only:[:new]

  resources :items do
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
    resources :image
  
    resources :items   do
      resources :buys do
        collection do
          post 'pay', to: 'buys#pay'
        end
      end
    end

  resources :buys, only: [:show]
  end
  
  

  resources :credit_cards, only: [:new, :create, :show, :destroy] do
  end

end

app/controllers/address_controller.rb
class AddressController < ApplicationController
  def new
  end
end

app/views/address/new.html.haml
.content
  %header
    = render 'mypage/my-page-header'
  .main-content
    .right-content
      .right-content__container
        %h2.right-content__container__head
          発送元・お届け先住所変更
        .right-content__container__box
          .right-content__container__box__form
            .right-content__container__box__form__group
              %label.right-content__container__box__form__group__label お名前
              %span.right-content__container__box__form__group__span 必須
              %input.right-content__container__box__form__group__input{type:"text", placeholder:"例）山田"}
              %input.right-content__container__box__form__group__input{type:"text", placeholder:"例）太郎"}
            .right-content__container__box__form__group
              %label.right-content__container__box__form__group__label お名前カナ
              %span.right-content__container__box__form__group__span 必須
              %input.right-content__container__box__form__group__input{type:"text", placeholder:"例）ヤマダ"}
              %input.right-content__container__box__form__group__input{type:"text", placeholder:"例）タロウ"}
            .right-content__container__box__form__group
              %label.right-content__container__box__form__group__label 郵便番号
              %span.right-content__container__box__form__group__span 必須
              %input.right-content__container__box__form__group__input{type:"text", placeholder:"例）123-4567", maxlength:"8"}
            .right-content__container__box__form__group
              %label.right-content__container__box__form__group__label 都道府県
              %span.right-content__container__box__form__group__span 必須
              .right-content__container__box__form__group__select-wrap
                %select.right-content__container__box__form__group__select-wrap__select-default
                  %option 選択してください
                  %option{:value => "0"} 北海道
                  %option{:value => "1"} 青森県
                  %option{:value => "2"} 岩手県
                  %option{:value => "3"} 宮城県
                  %option{:value => "4"} 秋田県
                  %option{:value => "5"} 山形県
                  %option{:value => "6"} 福島県
                  %option{:value => "7"} 茨城県
                  %option{:value => "8"} 栃木県
                  %option{:value => "9"} 群馬県
                  %option{:value => "10"} 埼玉県
                  %option{:value => "11"} 千葉県
                  %option{:value => "12"} 東京都
                  %option{:value => "13"} 神奈川県
                  %option{:value => "14"} 新潟県
                  %option{:value => "15"} 富山県
                  %option{:value => "16"} 石川県
                  %option{:value => "17"} 福井県
                  %option{:value => "18"} 山梨県
                  %option{:value => "19"} 長野県
                  %option{:value => "20"} 岐阜県
                  %option{:value => "21"} 静岡県
                  %option{:value => "22"} 愛知県
                  %option{:value => "23"} 三重県
                  %option{:value => "24"} 滋賀県
                  %option{:value => "25"} 京都府
                  %option{:value => "26"} 大阪府
                  %option{:value => "27"} 兵庫県
                  %option{:value => "28"} 奈良県
                  %option{:value => "29"} 和歌山県
                  %option{:value => "30"} 鳥取県
                  %option{:value => "31"} 島根県
                  %option{:value => "32"} 岡山県
                  %option{:value => "33"} 広島県
                  %option{:value => "34"} 山口県
                  %option{:value => "35"} 徳島県
                  %option{:value => "36"} 香川県
                  %option{:value => "37"} 愛媛県
                  %option{:value => "38"} 高知県
                  %option{:value => "39"} 福岡県
                  %option{:value => "40"} 佐賀県
                  %option{:value => "41"} 長崎県
                  %option{:value => "42"} 熊本県
                  %option{:value => "43"} 大分県
                  %option{:value => "44"} 宮崎県
                  %option{:value => "45"} 鹿児島県
                  %option{:value => "46"} 沖縄県
                  %option{:value => "47"} 未定
            .right-content__container__box__form__group
              %label.right-content__container__box__form__group__label 市区町村
              %span.right-content__container__box__form__group__span 必須
              %input.right-content__container__box__form__group__input{type:"text", placeholder:"例）大阪府堺市"}
            .right-content__container__box__form__group
              %label.right-content__container__box__form__group__label 番地
              %span.right-content__container__box__form__group__span 必須
              %input.right-content__container__box__form__group__input{type:"text", placeholder:"例）渋谷1-1"}
            .right-content__container__box__form__group
              %label.right-content__container__box__form__group__label 建物名
              %span.right-content__container__box__form__group__span-arbitrary 任意
              %input.right-content__container__box__form__group__input{type:"text", placeholder:"例）さかいビル"}
            .right-content__container__box__form__group
              %label.right-content__container__box__form__group__label 電話番号
              %span.right-content__container__box__form__group__span-arbitrary 任意
              %input.right-content__container__box__form__group__input{type:"number", placeholder:"例）09012345678"}
            %button.right-content__container__box__form__btn{type:"submit"} 変更する
    .left-content
      .my-page-bar
        %ul.my-page-bar__ul
          %li.my-page-bar__ul__list
            = link_to new_mypage_path do
              マイページ
          %li.my-page-bar__ul__list
            = link_to new_item_path do
              出品する
          %li.my-page-bar__ul__list
            = link_to new_inquiry_path do
              お問い合わせ
        %h3.my-page-bar__head
          設定
        %ul.my-page-bar__ul
          %li.my-page-bar__ul__list
            = link_to new_profile_path do
              プロフィール
          %li.my-page-bar__ul__list
            = link_to new_address_path do
              発送元・お届け先住所変更
          %li.my-page-bar__ul__list
            = link_to new_credit_card_path do
              支払い方法
          %li.my-page-bar__ul__list
            = link_to new_mail_password_path do
              メール/パスワード
          %li.my-page-bar__ul__list
            = link_to new_user_info_path do
              本人情報 
          %li.my-page-bar__ul__list
            = link_to "#" do
              電話番号の確認
          %li.my-page-bar__ul__list
            = link_to new_logout_path do
              ログアウト
= render 'items/footer'