config/routes.rb
Rails.application.routes.draw do
  get 'rename/categories'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profiles'
    post 'profiles', to: 'users/registrations#create_profiles'
  end
  
  root 'items#index'
  resources :credit_cards, only:[:new]
  resources :mypage, only:[:new]
  resources :address, only:[:new]
  resources :inquiry, only:[:new]
  resources :logout, only:[:new]
  resources :mail_password, only:[:new]
  resources :profile, only:[:new]
  resources :user_info, only:[:new]

  resources :items do
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
    resources :image
  
    resources :items   do
      resources :buys do
        collection do
          post 'pay', to: 'buys#pay'
        end
      end
    end

  resources :buys, only: [:show]
  end
  
  

  resources :credit_cards, only: [:new, :create, :show, :destroy] do
  end

end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  belongs_to :plofile, optional: true
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require "payjp"

  def new
    @card = CreditCard.where(user_id: current_user.id)
    redirect_to credit_card_path(current_user.id) if @card.exists? #showアクションにリダイレクト
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if params["payjp_token"].blank?
      redirect_to new_credit_card_path
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params["payjp_token"],
        metadata: {user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to  credit_card_path(@card)
      else
        redirect_to  new_credit_card_path
      end
    end
  end

  def show
    @card = CreditCard.find_by(user_id: current_user.id) #ログインユーザーの登録の有無
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id) #ログインユーザーの情報を取り出す
      @customer_card = customer.cards.retrieve(@card.card_id) #顧客情報からカードの情報を取り出す
      @exp_month = @customer_card.exp_month.to_s #有効期限（月）
      @exp_year = @customer_card.exp_year.to_s.slice(2,3) #有効期限（年）
    end
  end
  
  def destroy
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      if @card.destroy
        redirect_to root_path
      end
  end
end

app/views/credit_cards/new.html.haml
= render "items/header"
.credit-main
  .credit-main__product-continer
    %h2.credit-main__product-continer__title
      クレジットカード情報入力
  = form_tag(credit_cards_path, method: :post, id: "charge-form", class: "details", name: "inputForm") do  
    .credit-main__product-continer__inner
      %ul.credit-main__product-continer__inner__head-line
        %li.credit-main__product-continer__inner__head-line__card-number
          カード番号
          %span.required
            必須
      = text_field_tag "number", "", class: "input__default", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      %ul.credit-main__product-continer__inner__credit-icon-box
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_visa.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_master.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_saison.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_jcb.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_american.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_diners.png'), size: '45x28'
      %ul.credit-main__product-continer__inner__head-line
        %li.credit-main__product-continer__inner__head-line__card-number
          有効期限
          %span.required
            必須
      .credit-main__product-continer__inner__select
        %select#payment_card_month.credit-main__product-continer__inner__select__box{name: "payment_card_month", type: "text"}
          %option 01
          %option{value: "0"} 02
          %option{value: "1"} 03
          %option{value: "2"} 04
          %option{value: "3"} 05
          %option{value: "4"} 06
          %option{value: "5"} 07
          %option{value: "6"} 08
          %option{value: "7"} 09
          %option{value: "8"} 10
          %option{value: "9"} 11
          %option{value: "10"} 12
        .credit-main__product-continer__inner__select__icon
          = icon("fas", "chevron-down")
          %span.credit-day
            月
        %select#payment_card_year.credit-main__product-continer__inner__select__box{name: "payment_card_year", type: "text"}
          %option{value: "2020"} 20
          %option{value: "2021"} 21
          %option{value: "2022"} 22
          %option{value: "2023"} 23
          %option{value: "2024"} 24
          %option{value: "2025"} 25
          %option{value: "2026"} 26
          %option{value: "2027"} 27
          %option{value: "2028"} 28
          %option{value: "2029"} 29
          %option{value: "2030"} 30
        .credit-main__product-continer__inner__select__icon
          = icon("fas", "chevron-down")
          %span.credit-day
            年
      %ul.credit-main__product-continer__inner__head-line
        %li.credit-main__product-continer__inner__head-line__card-number
          セキュリテイコード
          %span.required
            必須
      = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面3~4桁の番号'
      .credit-main__product-continer__inner__question
        ?カード裏面の番号とは？
      .credit-main__product-continer__inner__btn
        = submit_tag "追加する", class: "add__btn", id: "payment_card_submit-button"
= render "items/exisibition"
= render "items/footer"

app/views/credit_cards/show.html.haml
.content
  %h1.content__head
    登録クレジットカード情報
  .content__main
    .content__main__text
      クレジットカード一覧
    .content__main__form
      .content__main__form__credit
        .content__main__form__credit__image
          = image_tag asset_path('credit-icon/credit-card_visa.png'), size: '45x28'
        .content__main__form__credit__box
          .content__main__form__credit__box__number
            = "**** **** **** " + @customer_card.last4
          .content__main__form__credit__box__deadline
            有効期限 05/20
          .expiration_date__info
            = @exp_month + " / " + @exp_year  #showメソッドで定義した有効期限の年と月を取得
      .content__main__home
        = link_to new_mypage_path class: "mypage__link" do
          マイページに戻る
      .content__main__form__delete
        = link_to "#", method: :delete, class: "content__main__form__delete__btn" do 
          削除する
    .content__main__bottom-text
      = link_to '支払い方法について'