config/routes.rb
Rails.application.routes.draw do
  get 'rename/categories'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profiles'
    post 'profiles', to: 'users/registrations#create_profiles'
  end
  
  root 'items#index'
  resources :credit_cards, only:[:new]
  resources :mypage, only:[:new]
  resources :address, only:[:new]
  resources :inquiry, only:[:new]
  resources :logout, only:[:new]
  resources :mail_password, only:[:new]
  resources :profile, only:[:new]
  resources :user_info, only:[:new]

  resources :items do
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
    resources :image
  
    resources :items   do
      resources :buys do
        collection do
          post 'pay', to: 'buys#pay'
        end
      end
    end

  resources :buys, only: [:show]
  end
  
  

  resources :credit_cards, only: [:new, :create, :show, :destroy] do
  end

end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  require 'payjp'
  before_action :check
  before_action :set_card
  before_action :set_item, only: [:show]
  def check
    if user_signed_in?
      set_card
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @items = Item.includes(:images).order('created_at DESC')
  end

  def pay
    @item = Item.find(params[:item_id])
    @card = CreditCard.where(user_id: current_user.id).first
    if @card.present?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      Payjp::Charge.create(
        amount: @item.price_id, #支払金額
        customer: @card.customer_id, #顧客ID
        currency: 'jpy', #日本円
      )
      @item.buyer_id = current_user.id
      @item.destroy
      redirect_to root_path, alert: '購入しました'
    else
      redirect_to new_credit_card_path,alert: '購入出来ません/クレジットカードの登録をしてください'
    end
  end

  private

  def set_card
    @card = CreditCard.where(user_id: current_user.id).first if CreditCard.where(user_id: current_user.id).present?
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/views/buys/show.html.haml
%header.header-icon-only
  .header-icon-only__title
    -# = link_to root_path
    = image_tag asset_path('material/logo/logo.png'), size: '185x49'
.confirmation
  .confirmation__main
    %section.confirmation__main__product-continer
      %h2.confirmation__main__product-continer__title
        購入内容の確認
      .confirmation__main__product-continer__buy-item
        .confirmation__main__product-continer__buy-item__inner
          .confirmation__main__product-continer__buy-item__inner__box
            .confirmation__main__product-continer__buy-item__inner__box__item-image
              - @item.images.each do |image|
                = image_tag image.image.to_s, size: "100x100", class: "png"
            .confirmation__main__product-continer__buy-item__inner__box__item-detail
              .confirmation__main__product-continer__buy-item__inner__box__item-detail__name
              
              %span.confirmation__main__product-continer__buy-item__inner__box__item-detail__price
                = "¥" + @item.price_id.to_s
                %span.confirmation__main__product-continer__buy-item__inner__box__item-detail__price__included
                  （税込）送料込み
      .confirmation__main__product-continer__payment
        .confirmation__main__product-continer__payment__inner
          -# form_withまたはform_forで実装
          %ul.confirmation__main__product-continer__payment__inner__price-table
            %li.confirmation__main__product-continer__payment__inner__price-table__label
              支払い金額
            %li.confirmation__main__product-continer__payment__inner__price-table__price
              %span.confirmation__main__product-continer__payment__inner__price-table__label__price__decoration
                = "¥" + @item.price_id.to_s
          %ul.confirmation__main__product-continer__payment__inner__point-table
            %li.confirmation__main__product-continer__payment__inner__point-table__point-use
              .confirmation__main__product-continer__payment__inner__point-table__point-use__check-box
                □
                -# のちにアイコンに置き換え
              .confirmation__main__product-continer__payment__inner__point-table__point-use__content
                ポイントを使用 (所持ポイント: P0)
      .confirmation__main__product-continer__payment-method
        .confirmation__main__product-continer__payment-method__inner
          支払い方法
          .confirmation__main__product-continer__payment-method__inner__link
            = link_to new_credit_card_path do
              変更する
            %p.confirmation__main__product-continer__payment-method__inner__link__icon
              %span.confirmation__main__product-continer__payment-method__inner__link__icon__registration
      .confirmation__main__product-continer__buy-user-text
        .purchase__confirmation__main__payment__card__info__number
          - if @default_card_information.blank?
            %br 
          - else
            = "**** **** **** " + @customer_card.last4
          .purchase__confirmation__main__payment__card__info__monthyear
            - exp_month =@customer_card.to_s
            - exp_year = @customer_card.to_s.slice(2,3)
          .confirmation__main__product-continer__buy-user-text__info-text__btn
            = link_to  pay_item_item_buys_path(item_id: @item.id), method: :post, class: "btn" do
              購入する
= render 'items/footer'            