config/routes.rb
Rails.application.routes.draw do
  get 'rename/categories'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profiles'
    post 'profiles', to: 'users/registrations#create_profiles'
  end
  
  root 'items#index'
  resources :credit_cards, only:[:new]
  resources :mypage, only:[:new]
  resources :address, only:[:new]
  resources :inquiry, only:[:new]
  resources :logout, only:[:new]
  resources :mail_password, only:[:new]
  resources :profile, only:[:new]
  resources :user_info, only:[:new]

  resources :items do
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
    resources :image
  
    resources :items   do
      resources :buys do
        collection do
          post 'pay', to: 'buys#pay'
        end
      end
    end

  resources :buys, only: [:show]
  end
  
  

  resources :credit_cards, only: [:new, :create, :show, :destroy] do
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images,inverse_of: :item, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :categorie, optional: true
  belongs_to :user, optional: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :derivery_fee
  belongs_to_active_hash :shipping_area
  belongs_to_active_hash :days_untill_shipping
  validates :images, presence: true, length: {manimum: 1, maximum: 10}
  validates :name,length: { in: 1..40 }
  validates :explanation,length: { in: 1..1000 }
  validates :price_id, numericality: { less_than_or_equal_to: 9999999, greater_than_or_equal_to: 300 }
  validates :categorie_id, :condition_id, :derivery_fee_id,
            :shipping_area_id, :days_untill_shipping_id, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:edit,:show,:destroy,:update]
  
  def index
    @items = Item.all
  end

  def new
    if user_signed_in?
      @category = Categorie.all.order("ancestry,id").limit(13)
      @item = Item.new
      @item.images.new
    else
      redirect_to new_user_session_path
    end
  end
  
  def show
    @items = Item.includes(:images).order('created_at DESC')
    @user = User.find_by(id: @item.seller_id)
  end

  def create
    @item = Item.new(item_params)
    if  @item.save
      redirect_to root_path, notice: '出品完了しました'
    else
      flash[:alert] = '出品できませんでした'
      redirect_to action: "new"
    end
  end

  def edit
    @category = Categorie.order("ancestry,id").limit(13)
    # 親セレクトボックスの初期値
    @category_parent_array = Categorie.where(ancestry: nil)
    @category_child_array = @item.categorie.parent.parent.children
    @category_grandchild_array = @item.categorie.parent.children
  end

  def update
    if  @item.update(item_params)
      redirect_to root_path, notice: '編集完了しました'
    else
      flash[:alert] = '編集できませんでした'
      redirect_to action: "edit"
    end
  end

  def destroy
    if user_signed_in? && current_user.id == @item.seller_id
      if @item.destroy
        redirect_to root_path, notice: '削除が完了しました'
      else
        redirect_to root_path, alert: '削除できませんでした'
      end
    else
      redirect_to root_path, alert: '権限がありません'
    end
  end

  def category_children
    @category_children = Categorie.find(params[:productcategory]).children 
  end
    
  def category_grandchildren
    @category_grandchildren = Categorie.find(params[:productcategory]).children
  end
  
private
  def item_params
    params.require(:item).permit(:name, :price_id, :explanation, :categorie_id, :size, :condition_id, :derivery_fee_id, :shipping_area_id, :days_untill_shipping_id, images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id)
  end
  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_app-banner.html.haml
.main__app-banner
  .main__app-banner__inner
    %h2.main__app-banner__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.main__app-banner__inner__text
      今すぐ無料ダウンロード！
    .main__app-banner__inner__btn
      -# = link_to "APP store"
      -# = link_to "Google"

app/views/items/_confirmation.html.haml
%header.header-icon-only
  .header-icon-only__title
    -# = link_to root_path
    = image_tag asset_path('material/logo/logo.png'), size: '185x49'
.confirmation
  .confirmation__main
    %section.confirmation__main__product-continer
      %h2.confirmation__main__product-continer__title
        購入内容の確認
      .confirmation__main__product-continer__buy-item
        .confirmation__main__product-continer__buy-item__inner
          .confirmation__main__product-continer__buy-item__inner__box
            .confirmation__main__product-continer__buy-item__inner__box__item-image
              = image_tag asset_path('material/icon/member_photo_noimage_thumb.png')
            .confirmation__main__product-continer__buy-item__inner__box__item-detail
              .confirmation__main__product-continer__buy-item__inner__box__item-detail__name
                顔イメージ
              %span.confirmation__main__product-continer__buy-item__inner__box__item-detail__price
                ¥200
                %span.confirmation__main__product-continer__buy-item__inner__box__item-detail__price__included
                  （税込）送料込み
      .confirmation__main__product-continer__payment
        .confirmation__main__product-continer__payment__inner
          -# form_withまたはform_forで実装
          %ul.confirmation__main__product-continer__payment__inner__price-table
            %li.confirmation__main__product-continer__payment__inner__price-table__label
              支払い金額
            %li.confirmation__main__product-continer__payment__inner__price-table__price
              %span.confirmation__main__product-continer__payment__inner__price-table__label__price__decoration
                ¥880
          %ul.confirmation__main__product-continer__payment__inner__point-table
            %li.confirmation__main__product-continer__payment__inner__point-table__point-use
              .confirmation__main__product-continer__payment__inner__point-table__point-use__check-box
                □
                -# のちにアイコンに置き換え
              .confirmation__main__product-continer__payment__inner__point-table__point-use__content
                ポイントを使用 (所持ポイント: P0)
      .confirmation__main__product-continer__payment-method
        .confirmation__main__product-continer__payment-method__inner
          支払い方法
          .confirmation__main__product-continer__payment-method__inner__link
            -# リンク先を入れる
            %p.confirmation__main__product-continer__payment-method__inner__link__icon
              +
              %span.confirmation__main__product-continer__payment-method__inner__link__icon__registration
                登録してください
      .confirmation__main__product-continer__shipping-address
        .confirmation__main__product-continer__shipping-address__inner
          配送先
          .confirmation__main__product-continer__shipping-address__inner__link
            -# リンク先を入れる
            %p.confirmation__main__product-continer__shipping-address__inner__link__icon
              +
              %span.confirmation__main__product-continer__shipping-address__inner__link__icon__registration
                登録してください
      .confirmation__main__product-continer__buy-user-text
        %p.confirmation__main__product-continer__buy-user-text__info-text
          郵便局/コンビニ受取をご希望の方は、購入後に
          %span
            取引画面
          から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
          .confirmation__main__product-continer__buy-user-text__info-text__btn
            購入する

app/views/items/_credit-card.html.haml
= render "header"
.credit-main
  .credit-main__product-continer
    %h2.credit-main__product-continer__title
      クレジットカード情報入力
    -# .credit-main__product-continer
      form_withを使用する
    .credit-main__product-continer__inner
      %ul.credit-main__product-continer__inner__head-line
        %li.credit-main__product-continer__inner__head-line__card-number
          カード番号
          %span.required
            必須
      %input.credit-main__product-continer__inner__text-box{type: "text", placeholder: "半角数字のみ"}
      %ul.credit-main__product-continer__inner__credit-icon-box
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_visa.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_master.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_saison.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_jcb.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_american.png'), size: '45x28'
        %li.credit-main__product-continer__inner__credit-icon-box__icon
          = image_tag asset_path('credit-icon/credit-card_diners.png'), size: '45x28'
      %ul.credit-main__product-continer__inner__head-line
        %li.credit-main__product-continer__inner__head-line__card-number
          有効期限
          %span.required
            必須
      .credit-main__product-continer__inner__select
        %select.credit-main__product-continer__inner__select__box
          %option 01
          %option{value: "0"} 02
          %option{value: "1"} 03
          %option{value: "2"} 04
          %option{value: "3"} 05
          %option{value: "4"} 06
          %option{value: "5"} 07
          %option{value: "6"} 08
          %option{value: "7"} 09
          %option{value: "8"} 10
          %option{value: "9"} 11
          %option{value: "10"} 12
        .credit-main__product-continer__inner__select__icon
          = icon("fas", "chevron-down")
          %span.credit-day
            月
        %select.credit-main__product-continer__inner__select__box
          %option 20
          %option{value: "0"} 21
          %option{value: "1"} 22
          %option{value: "2"} 23
          %option{value: "3"} 24
          %option{value: "4"} 25
          %option{value: "5"} 26
          %option{value: "6"} 27
          %option{value: "7"} 28
          %option{value: "8"} 29
          %option{value: "9"} 30
        .credit-main__product-continer__inner__select__icon
          = icon("fas", "chevron-down")
          %span.credit-day
            年
      %ul.credit-main__product-continer__inner__head-line
        %li.credit-main__product-continer__inner__head-line__card-number
          セキュリテイコード
          %span.required
            必須
      %input.credit-main__product-continer__inner__text-box{type: "text", placeholder: "カード背面４桁もしくは３桁の番号"}
      .credit-main__product-continer__inner__question
        ?カード裏面の番号とは？
      .credit-main__product-continer__inner__btn
        追加する
= render "exisibition"
= render "footer"

app/views/items/_exisibition.html.haml
= link_to new_item_path do
  .main__exisibition
    %span.main__exisibition__text
      出品する
    .main__exisibition__icon
      = image_tag asset_path('material/icon/icon_camera.png'), size: '50x50'

app/views/items/_footer.html.haml
%footer.main-footer
  %ul.main-footer__contents
    %li.main-footer__contents__content
      %h2.main-footer__contents__content__header
        FURIMAについて
      %ul.main-footer__contents__content__about
        %li.main-footer__contents__content__about__over-view
          = link_to "#" do
            会社概要（運営会社）
          = link_to "#" do
            プライバシーポリシー
          = link_to "#" do
            FURIMA利用規約
          = link_to "#" do
            ポイントに関する特約

    %li.main-footer__contents__content
      %h2.main-footer__contents__content__header
        FURIMAを見る
      %ul.main-footer__contents__content__about
        %li.main-footer__contents__content__about__over-view
          = link_to "#" do
            カテゴリー一覧
          = link_to "#" do
            ブランド一覧

    %li.main-footer__contents__content
      %h2.main-footer__contents__content__header
        ヘルプ&ガイド
      %ul.main-footer__contents__content__about
        %li.main-footer__contents__content__about__over-view
          = link_to "#" do
            FURIMAガイド
          = link_to "#" do
            FURIMAロゴ利用ガイドライン
          = link_to "#" do
            お知らせ
  .main-footer__footer-logo
    = image_tag asset_path("material/logo/logo-white.png")
    %p.main-footer__footer-logo__copy-right
      © FURIMA

app/views/items/_header.html.haml
%header.header
  .header__header-inner
    .header__header-inner__main-header
      %h1.header__header-inner__main-header__icon
        = link_to root_path do
          = image_tag 'material/logo/logo.png', size: '140x40'
      .header__header-inner__main-header__search-box
        .header__header-inner__main-header__search-box__text
          %input.header__header-inner__main-header__search-box__text__input{type: "text", placeholder: "キーワードから探す"}
          %input.header__header-inner__main-header__search-box__text__btn{type: "submit", value: ""}
            .header__header-inner__main-header__search-box__text__btn__search-btn
              = image_tag 'material/icon/icon-search 1.png', size: '20x20'
    .header__header-inner__category
      %ul.header__header-inner__category__left-box
        %li.header__header-inner__category__left-box__right-item
          = link_to "ブランド"
      %ul.header__header-inner__category__right-box
        %li.header__header-inner__category__right-box__left-item
        - if user_signed_in?
          = link_to 'ログアウト', destroy_user_session_path, method: :delete
          = link_to 'マイページ', new_mypage_path(current_user)
        - else
          = link_to "ログイン", new_user_session_path
          = link_to new_user_registration_path do
            新規会員登録

app/views/items/_main.html.haml
.main__main-visual
  .main__main-visual__content
    %h2.main__main-visual__content__subtitle
      %br
      人生を変えるフリマアプリ
    %p.main__main-visual__content__text
      FURIMAはだれでもかんたんに出品・購入できる
      %br
      フリマアプリです
    .main__main-visual__content__btn
      -# = link_to "APP store"
      -# = link_to "Google"
.main__top-introduction
  %h2.main__top-introduction__subtitle
    FURIMAが選ばれる3つの理由
    .main__top-introduction__subtitle__line
  %ul.main__top-introduction__list-box
    %li.main__top-introduction__list-box__list
      .main__top-introduction__list-box__list__pict
        %span.main__top-introduction__list-box__list__pict__number
          1
        = image_tag asset_path('material/pict/pict-reason-01.jpg')
      %h3.main__top-introduction__list-box__list__text
        %span.name
          3分
        ですぐに出品
      .main__top-introduction__list-box__list__sub-text
        スマホで入力するだけで簡単に出品できる！
    %li.main__top-introduction__list-box__list
      .main__top-introduction__list-box__list__pict
        %span.main__top-introduction__list-box__list__pict__number
          ２
        = image_tag asset_path('material/pict/pict-reason-02.jpg')
      %h3.main__top-introduction__list-box__list__text
        %span.name
          シンプル
        で使いやすい
      .main__top-introduction__list-box__list__sub-text
        めんどくさい入力は必要なく、検索も購入もスムーズ！
    %li.main__top-introduction__list-box__list
      .main__top-introduction__list-box__list__pict
        %span.main__top-introduction__list-box__list__pict__number
          ３
        = image_tag asset_path('material/pict/pict-reason-03.jpg')
      %h3.main__top-introduction__list-box__list__text
        手数料
        %span.name
          業界最安
      .main__top-introduction__list-box__list__sub-text
        最大3%でお得に出品&購入！
.main__middle-introduction
  .main__middle-introduction__inner
    %h2.main__middle-introduction__inner__sub-title
      会員数日本一位
    %p.main__middle-introduction__inner__text
      FURIMAは、フリマアプリで最も人気。
      %br
      出品・購入回数も業界最多です！
      %br
      ほしかったあの商品に出会えるかもしれません。
    .main__middle-introduction__inner__btn
      -# = link_to "APP store"
      -# = link_to "Google"
.main__characteristic
  %h2.main__characteristic__head
    FURIMAの特徴
    .main__characteristic__head__line
  .main__characteristic__item-box
    .main__characteristic__item-box__item
      .main__characteristic__item-box__item__img
        = image_tag asset_path('material/icon/icon-01.png')
      %h3.main__characteristic__item-box__item__sub-title
        簡単に売り買いできる
      %p.main__characteristic__item-box__item__detail
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    .main__characteristic__item-box__item
      .main__characteristic__item-box__item__img
        = image_tag asset_path('material/icon/icon-03.png')
      %h3.main__characteristic__item-box__item__sub-title
        売上金は即日振込みに対応
      %p.main__characteristic__item-box__item__detail
        午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
    .main__characteristic__item-box__item
      .main__characteristic__item-box__item__img
        = image_tag asset_path('material/icon/icon-04.png')
      %h3.main__characteristic__item-box__item__sub-title
        様々な支払いに対応
      %p.main__characteristic__item-box__item__detail
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
.main__pickup-category
  %h2.main__pickup-category__title
    ピックアップカテゴリー
  .main__pickup-category__product-box
    .main__pickup-category__product-box__head
      新規投稿商品
    .main__pickup-category__product-box__lists
      - @items.last(3).each do |item|
        = link_to item_path(item.id) do
          .main__pickup-category__product-box__lists__list
            .main__pickup-category__product-box__lists__list__img
              = image_tag item.images&.first&.image.to_s
            .main__pickup-category__product-box__lists__list__body
              %h3.main__pickup-category__product-box__lists__list__body__name
                = item.name              
              .main__pickup-category__product-box__lists__list__body__details
                %ul.main__pickup-category__product-box__lists__list__body__details__box
                  %li.main__pickup-category__product-box__lists__list__body__details__box__money
                    = item.price_id
                    円
                  %li.main__pickup-category__product-box__lists__list__body__details__box__star
                    ★ 0
                %p.main__pickup-category__product-box__lists__list__body__details__tax
                  (税込)
.main__pickup-category
  %h2.main__pickup-category__title
    ピックアップブランド
  .main__pickup-category__product-box
    .main__pickup-category__product-box__head
      アーカイブ
    .main__pickup-category__product-box__lists
      - @items.last(3).each do |item|
        = link_to item_path(item.id) do
          .main__pickup-category__product-box__lists__list
            .main__pickup-category__product-box__lists__list__img
              = image_tag item.images&.first&.image.to_s
            .main__pickup-category__product-box__lists__list__body
              %h3.main__pickup-category__product-box__lists__list__body__name
                = item.name              
              .main__pickup-category__product-box__lists__list__body__details
                %ul.main__pickup-category__product-box__lists__list__body__details__box
                  %li.main__pickup-category__product-box__lists__list__body__details__box__money
                    = item.price_id
                  %li.main__pickup-category__product-box__lists__list__body__details__box__star
                    ★ 0
                %p.main__pickup-category__product-box__lists__list__body__details__tax
                  (税込)

app/views/items/_show.html.haml
= render "header"
.main
  .main__show-main
    .main__show-main__content-right
      .main__show-main__content-right__top-content
        .main__show-main__content-right__top-content__item-box
          %h2.main__show-main__content-right__top-content__item-box__name product3
          .main__show-main__content-right__top-content__item-box__body
            %ul.main_image
              %li.main_photo
                = image_tag asset_path('material/show/main.png'), size: "560x346"
                %ul.show_index
                  %li.show_index__content
                    = image_tag asset_path('material/show/index1.png'), size: "130x87", class: "png"
                  %li.show_index__content
                    = image_tag asset_path('material/show/index2.png'), size: "130x87", class: "png"
                  %li.show_index__content
                    = image_tag asset_path('material/show/index3.png'), size: "130x87", class: "png"
          .main__show-main__content-right__top-content__item-box__price
            %span.font-size ¥30000
            .main__show-main__content-right__top-content__item-box__price__detail
              %span.tax （税込）
              %span.derivery-fee 送料込み
          .main__show-main__content-right__top-content__item-box__item-detail
            商品説明、商品説明、商品説明、商品説明、商品説明、商品説明、商品説明、商品説明、商品説明、
            商品説明、商品説明、商品説明、商品説明、商品説明、商品説明
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td yurie
                %tr
                  %th カテゴリー
                  %td
                    = link_to "#" do
                      %span ベビー・キッズ
                    %br  
                    = link_to "#" do
                      %span ベビー服（男女兼用）　~95cm
                    %br
                    = link_to "#" do
                      %span アウター
                %tr
                  %th ブランド
                  %td 
                %tr
                  %th 商品のサイズ
                  %td
                %tr
                  %th 商品の状態
                  %td 未使用に近い
                %tr
                  %th 配送料の負担
                  %td 送料込み（出品者負担）
                %tr
                  %th 発送元の地域
                  %td
                    = link_to "#" do
                      岩手県
                %tr
                  %th 発送日の目安
                  %td 4~7日で発送
      %ul.main__show-main__content-right__top-content__links
        %li
          = link_to "#" do
            %i.fa.angele-left
            .item-link < 前の商品
        %li
          = link_to "#" do
            .item-link 後ろの商品 >
            %i.fa.angele-right
      .related-items
        = link_to "#" do
          %span ベビーキッズをもっと見る
        .product-lists
-# = render "footer"

app/views/items/confirmation.html.haml
%header.header-icon-only
  .header-icon-only__title
    -# = link_to root_path
    = image_tag asset_path('material/logo/logo.png'), size: '185x49'
.confirmation
  .confirmation__main
    %section.confirmation__main__product-continer
      %h2.confirmation__main__product-continer__title
        購入内容の確認
      .confirmation__main__product-continer__buy-item
        .confirmation__main__product-continer__buy-item__inner
          .confirmation__main__product-continer__buy-item__inner__box
            .confirmation__main__product-continer__buy-item__inner__box__item-image
              = image_tag asset_path('material/icon/member_photo_noimage_thumb.png')
            .confirmation__main__product-continer__buy-item__inner__box__item-detail
              .confirmation__main__product-continer__buy-item__inner__box__item-detail__name
                顔イメージ
              %span.confirmation__main__product-continer__buy-item__inner__box__item-detail__price
                ¥200
                %span.confirmation__main__product-continer__buy-item__inner__box__item-detail__price__included
                  （税込）送料込み
      .confirmation__main__product-continer__payment
        .confirmation__main__product-continer__payment__inner
          -# form_withまたはform_forで実装
          %ul.confirmation__main__product-continer__payment__inner__price-table
            %li.confirmation__main__product-continer__payment__inner__price-table__label
              支払い金額
            %li.confirmation__main__product-continer__payment__inner__price-table__price
              %span.confirmation__main__product-continer__payment__inner__price-table__label__price__decoration
                ¥880
          %ul.confirmation__main__product-continer__payment__inner__point-table
            %li.confirmation__main__product-continer__payment__inner__point-table__point-use
              .confirmation__main__product-continer__payment__inner__point-table__point-use__check-box
                □
                -# のちにアイコンに置き換え
              .confirmation__main__product-continer__payment__inner__point-table__point-use__content
                ポイントを使用 (所持ポイント: P0)
      .confirmation__main__product-continer__payment-method
        .confirmation__main__product-continer__payment-method__inner
          支払い方法
          .confirmation__main__product-continer__payment-method__inner__link
            -# リンク先を入れる
            %p.confirmation__main__product-continer__payment-method__inner__link__icon
              +
              %span.confirmation__main__product-continer__payment-method__inner__link__icon__registration
                登録してください
      .confirmation__main__product-continer__shipping-address
        .confirmation__main__product-continer__shipping-address__inner
          配送先
          .confirmation__main__product-continer__shipping-address__inner__link
            -# リンク先を入れる
            %p.confirmation__main__product-continer__shipping-address__inner__link__icon
              +
              %span.confirmation__main__product-continer__shipping-address__inner__link__icon__registration
                登録してください
      .confirmation__main__product-continer__buy-user-text
        %p.confirmation__main__product-continer__buy-user-text__info-text
          郵便局/コンビニ受取をご希望の方は、購入後に
          %span
            取引画面
          から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
          .confirmation__main__product-continer__buy-user-text__info-text__btn
            購入する

app/views/items/index.html.haml
= render "header"
.main
  = render "main"
  = render "app-banner"
  = render 'exisibition'
= render "footer"

app/views/items/show.html.haml
= render "header"
.main
  .main__show-main
    .main__show-main__content-right
      .main__show-main__content-right__top-content
        .main__show-main__content-right__top-content__item-box
          %h2.main__show-main__content-right__top-content__item-box__name 
            = @item.name
          .main__show-main__content-right__top-content__item-box__body
            %ul.main_image
              %li.main_photo
                = image_tag @item.images&.first&.image.to_s
                %ul.show_index
                  %li.show_index__content
                  - @item.images.each do |image|
                    = image_tag image.image.to_s, size: "130x87", class: "png"
          .main__show-main__content-right__top-content__item-box__price
            %span.font-size
              ¥
              = @item.price_id
            .main__show-main__content-right__top-content__item-box__price__detail
              %span.tax （税込）
              %span.derivery-fee 送料込み
          .main__show-main__content-right__top-content__item-box__item-detail
            = @item.explanation
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td 
                    = @user.nickname
                %tr
                  %th カテゴリー
                  %td
                    = link_to "#" do
                      %span
                        = @item.categorie.parent.parent.name
                    %br  
                    = link_to "#" do
                      %span 
                        = @item.categorie.parent.name
                    %br
                    = link_to "#" do
                      %span 
                        = @item.categorie.name
                -# %tr
                -#   %th ブランド
                -#   %td 
                %tr
                  %th 商品のサイズ
                  %td
                    = @item.size
                %tr
                  %th 商品の状態
                  %td 
                    = @item.condition.name
                %tr
                  %th 配送料の負担
                  %td 
                    = @item.derivery_fee.name
                %tr
                  %th 発送元の地域
                  %td 
                    = @item.shipping_area.name
                %tr
                  %th 発送日の目安
                  %td 
                    = @item.days_untill_shipping.name
            - if user_signed_in? && current_user.id == @item.seller_id
              = link_to edit_item_path(@item.id), class: "btn"  do
                編集する
              ／
              = link_to item_path(@item),method: :delete, class: "btn"  do
                削除する
            - else
              .buy__link
                = link_to  "購入画面へすすむ", item_buy_path(@item)          
      %ul.main__show-main__content-right__top-content__links
        %li
          = link_to "#" do
            .item-link < 前の商品
            %i.fa.angele-left
        %li
          = link_to "#" do
            .item-link 後ろの商品 >
            %i.fa.angele-right
      .related-items
        = link_to "#" do
          %span ベビーキッズをもっと見る
        .product-lists
        
= render "footer"